#!/bin/sh      
#permissions must include executable => sudo chmod +x deploy
# here's a note\, here's a change
ssh useradmin@165.227.61.128 <<EOF        
	cd ~/apps/gaccMapClient
	#sudo chown -R useradmin .
  # here's a change
	git pull origin master       
	yarn install --production=true
	pm2 stop server
	pm2 start server.js
	exit       
EOF

